site_name   : simpleset
site_url    : https://simpleset.readthedocs.io/en/latest/
site_author : "Ofer Nave <odigity@gmail.com>"
theme       : readthedocs
nav:
  - index.md
  - cheatsheet.md
  - customizing.md
  - integrations.md
  - error.md
  - internals.md
markdown_extensions:
    - toc:
        permalink: true
